# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

sudo: required
cache: packages

r_binary_packages: 
  - stringr
  - dplyr
  - igraph
  - RCurl
  - XML
  - git2r
  - devtools
  
warnings_are_errors: false

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpng-dev  
